services:
- type: web
  name: tododle
  env: python
  buildCommand: "pip install -r requirements.txt && FLASK_APP=main python -m flask db upgrade"
  startCommand: "gunicorn main:app -b 0.0.0.0:10000"
  envVars:
  - key: SECRET_KEY
    value: <your_secret_key>
  - key: DATABASE_URL
    value: <your_render_database_url>
